### PR TITLE
Upgrade library to support temporal sdk v1.4.0

### PR DESCRIPTION
**Pull request by Prashant-Surya**
- Updated temporal sdk to latest version.

### Testing Details:
- Verified the integration using a sample nest js app https://github.com/Prashant-Surya/nestjs-temporal-example

Screenshot 2022-10-03 at 8 00 30 PM

### CODE REVIEW

**Comment by Prashant-Surya** [comment]
@KurtzL could you please review this? We're planning to use this library in my current project.

**Comment by jdnichollsc** [comment]
Hey @Prashant-Surya, hope you're doing well
Can you share an example project using your changes please? I'm trying to use that but I can't create the connection while importing the module:

```ts
TempModule.forRootAsync({
  imports: [ConfigModule],
  inject: [ConfigService],
  useFactory: async (configSvc: ConfigService): Promise<WorkerOptions> => {
    const temporalHost = configSvc.get('app.temporalHost');
    const connection = await NativeConnection.connect({
      address: temporalHost,
    });
    return {
      connection,
      taskQueue: 'report-pipeline',
      workflowsPath: require.resolve('../workflows'),
    };
  },
}),
```

Any help is really appreciated! 
BTW, @amirsaber and I are testing this fork to support **NestJS** 9 as well <3

**Comment by Prashant-Surya** [comment]
Hey, I've added the sample nest js app where I tested in previous comment https://github.com/Prashant-Surya/nestjs-temporal-example 
You can check this and let me know if there's any issue.  
 
  On Sat, 8 Oct 2022 at 2:37, J.D ***@***.***> wrote:   


Hey @Prashant-Surya, hope you're doing well
Can you share an example project using your changes please? I'm trying to use that but I can't create the connection while importing the module:
TempModule.forRootAsync({
  imports: [ConfigModule],
  inject: [ConfigService],
  useFactory: async (configSvc: ConfigService): Promise<WorkerOptions> => {
    const temporalHost = configSvc.get('app.temporalHost');
    const connection = await NativeConnection.connect({
      address: temporalHost,
    });
    return {
      connection,
      taskQueue: 'report-pipeline',
      workflowsPath: require.resolve('../workflows'),
    };
  },
}),
Any help is really appreciated!
BTW, @amirsaber and I are testing this fork to support NestJS 9 as well <3

**Comment by Prashant-Surya** [comment]
FYI the above sample nestjs app uses nestjs 9 so you should be able to use my fork directly

**Comment by jdnichollsc** [comment]
@Prashant-Surya thanks for your amazing help [Surya Prashanth](https://github.com/Prashant-Surya), let me send you some fixes to your PR! <3

**Comment by jdnichollsc** [comment]
@Prashant-Surya this is the PR with my fixes, thanks mate for your help! <3 https://github.com/Prashant-Surya/nestjs-temporal/pull/1/files

**Comment by jdnichollsc** [comment]
#17 we fixed the support for NestJS 9 in this PR! <3

**Comment by jdnichollsc** [comment]
Hey @KurtzL, what do you think about this PR? thanks for your help! <3

**Comment by Prashant-Surya** [comment]
@jdnichollsc There were some issues with after migrating to nestjs 9. I've raised this PR with fixes. Could you check these as well? https://github.com/Prashant-Surya/nestjs-temporal/pull/2

**Comment by jdnichollsc** [comment]
Ohh looks good! I only tried the async methods! haha

**Comment by KurtzL** [comment]
Hello @Prashant-Surya @jdnichollsc . Thanks for your amazing work.

**Comment by jdnichollsc** [comment]
@KurtzL thanks to you! <3

**Pull request merged**
