### PR TITLE
Squashing client and worker shutdown errors

### LINKED ISSUE #38: Squash worker shutdown errors
I am migrating a service to use NestJS. The workers share a connection and client. Shutting down the service results in the error below. The client is most likely being shutdown before the worker. Admittedly, this is a problem of my own making; but, it would be ideal if this error were squashed and logged, rather than bubbling up.

```
[17:00:59.990] ERROR (49994): Error happened during shutdown
    context: "NestApplicationContext"
    err: {
      "type": "Error",
      "message": "Error happened during shutdown",
      "stack":
          IllegalStateError: Not running
              at Worker.shutdown (/Users/clintonb/vori/backend/node_modules/@temporalio/worker/src/worker.ts:755:13)
              at TemporalExplorer.onModuleDestroy (/Users/clintonb/vori/backend/node_modules/nestjs-temporal/dist/temporal.explorer.js:49:68)
              at MapIterator.iteratee (/Users/clintonb/vori/backend/node_modules/@nestjs/core/hooks/on-module-destroy.hook.js:22:43)
              at MapIterator.next (/Users/clintonb/vori/backend/node_modules/iterare/src/map.ts:9:39)
              at IteratorWithOperators.next (/Users/clintonb/vori/backend/node_modules/iterare/src/iterate.ts:19:28)
              at Function.from (<anonymous>)
              at IteratorWithOperators.toArray (/Users/clintonb/vori/backend/node_modules/iterare/src/iterate.ts:227:22)
              at callOperator (/Users/clintonb/vori/backend/node_modules/@nestjs/core/hooks/on-module-destroy.hook.js:23:10)
              at callModuleDestroyHook (/Users/clintonb/vori/backend/node_modules/@nestjs/core/hooks/on-module-destroy.hook.js:43:23)
              at NestApplication.callDestroyHook (/Users/clintonb/vori/backend/node_modules/@nestjs/core/nest-application-context.js:234:53)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at async process.cleanup (/Users/clintonb/vori/backend/node_modules/@nestjs/core/nest-application-context.js:188:17)
    }
```

https://github.com/KurtzL/nestjs-temporal/blob/4b0b0c58ced8af90c7ee42c1772e6468f808f6ec/lib/temporal.explorer.ts#L53

### PR DESCRIPTION
**Pull request by clintonb**
If the client connection or worker is not cleanly shutdown, a log entry is created and the exception is squashed. This ensures we don't unnecessarily crash systems that are already in the process of shutting down.

Fixes #38

### CODE REVIEW

**Comment by clintonb** [comment]
Actually...the shutdown isn't necessary at all. Temporal already listens for shutdown signals: https://typescript.temporal.io/api/interfaces/worker.RuntimeOptions#shutdownsignals.

**Comment by clintonb** [comment]
I'm also seeing a _client_ shutdown error during testing: 

https://github.com/KurtzL/nestjs-temporal/blob/4d8a948df329d93167223c6c711dcc185988b55a/lib/utils/client.util.ts#L4-L7

**Comment by clintonb** [comment]
Confirmed that client close is the source of my problems. This fixes them.

**Comment by clintonb** [comment]
@KurtzL is there a timeline for reviewing and merging?

**Review by KurtzL — APPROVED** [review]

**Pull request merged**
